http:
  port: "8082"
  
american:
  host: "training4-american-api-jyadav1.us-e2.cloudhub.io"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  client_id: "739fb72387454fae8d7a347ddccdb2ff"
  client_secret: "e9c5971C207043cbbD1C6ef9D71e7c6c"
  
training:
  host: "mu.learn.mulesoft.com"
  port: "80"
  basepath: "/"
  protocol: "HTTP"
  
delta:
  wsdl: "http://mu.learn.mulesoft.com/delta?wsdl"
  service: "TicketServiceService"
  port: "TicketServicePort"
  
  